apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: servicee-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1
    resource: serviceecontrols
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://servicee-controller.hello/sync
