apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: service-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1
    resource: servicecontrols
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://service-controller.service/sync
