apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicees.example.com
spec:
  group: example.com
  names:
    kind: Servicee
    plural: servicees
    singular: servicee
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
            description: "API version of the resource"
          kind:
            type: string
            description: "Kind of resource"
          spec:
            type: object
            description: "Specification of the Service"
            properties:
              OrgName:
                type: string
                description: "Organization name for the service"
              TeamName:
                type: string
                description: "Team name for the service"
              ServiceName:
                type: string
                description: "Name of the service"
              EnvironmentName:
                type: string
                description: "Name of the environment"
